FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY log_generator.go .

RUN go build -o log-generator log_generator.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/log-generator .

CMD ["./log-generator"]
