FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY main.go ./

RUN CGO_ENABLED=0 go build -o log-streamer .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/log-streamer .

CMD ["./log-streamer"]
